name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}] # se actualiza 2 veces al d√≠a
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JuanJaramillo12004
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: America/Bogota

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6

          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_filter: all
